import type { ArchiveRecord } from "./types";

export const SAMPLE_ARCHIVES: ArchiveRecord[] = [
  // ── Registre des fugitifs ──────────────────────────────────────────
  {
    id: "fug_001",
    type: "fugitif",
    name: "Marie-Joseph Angélique",
    age: "29 ans",
    date: "1734-04-10",
    location: "Montréal, Nouvelle-France",
    origin: "Madère (Portugal)",
    owner: "Thérèse de Couagne, veuve Francheville",
    source: "Archives nationales du Québec — Procès criminels, 1734",
    notes:
      "Connue pour avoir tenté de fuir vers la Nouvelle-Angleterre avec Claude Thibault.",
  },
  {
    id: "fug_002",
    type: "fugitif",
    name: "Louis dit Coffi",
    age: "32 ans",
    date: "1791-08-22",
    location: "Cap-Français, Saint-Domingue",
    origin: "Côte de l'Or",
    owner: "Habitation Galliffet",
    source: "Affiches américaines, n°68, 1791",
    notes: "Description : taille moyenne, marques d'initiation au visage.",
  },
  {
    id: "fug_003",
    type: "fugitif",
    name: "Rosalie",
    age: "24 ans",
    date: "1806-03-15",
    location: "Pointe-à-Pitre, Guadeloupe",
    origin: "Sénégambie",
    owner: "Sieur Pinel",
    source: "Gazette de la Guadeloupe, 1806",
    notes: "Récompense offerte de 50 livres tournois.",
  },
  {
    id: "fug_004",
    type: "fugitif",
    name: "Jean-Baptiste",
    age: "40 ans",
    date: "1822-11-02",
    location: "Saint-Pierre, Martinique",
    origin: "Né dans la colonie",
    owner: "Habitation Lajus",
    source: "Journal officiel de la Martinique, 1822",
    notes: "Parle français et créole. Marqué d'une cicatrice au bras gauche.",
  },
  {
    id: "fug_005",
    type: "fugitif",
    name: "Cécile",
    age: "19 ans",
    date: "1838-07-19",
    location: "La Nouvelle-Orléans, Louisiane",
    origin: "Née à Saint-Domingue",
    owner: "M. Dupré",
    source: "New Orleans Bee, 1838",
    notes: "Aurait rejoint la communauté marronne du bayou Lafourche.",
  },

  // ── Registre des affranchissements ─────────────────────────────────
  {
    id: "aff_001",
    type: "affranchissement",
    name: "Toussaint Bréda (Louverture)",
    date: "1776-12-25",
    location: "Saint-Domingue",
    owner: "Bayon de Libertat",
    source: "Acte notarié, étude Bordier",
    notes: "Affranchi à l'âge de 33 ans environ.",
  },
  {
    id: "aff_002",
    type: "affranchissement",
    name: "Marie-Jeanne",
    age: "28 ans",
    date: "1789-05-12",
    location: "Basse-Terre, Guadeloupe",
    owner: "Sieur de Léogane",
    source: "Registre d'affranchissement, ANOM",
    notes:
      "Affranchissement gratuit pour services rendus, avec ses deux enfants.",
  },
  {
    id: "aff_003",
    type: "affranchissement",
    name: "Pierre dit Beausoleil",
    age: "45 ans",
    date: "1815-09-30",
    location: "Cayenne, Guyane française",
    owner: "Veuve Charpentier",
    source: "ANOM, Série G — Affranchissements",
    notes: "Rachat de liberté pour la somme de 2 000 livres.",
  },
  {
    id: "aff_004",
    type: "affranchissement",
    name: "Rose-Aimée",
    age: "22 ans",
    date: "1831-02-18",
    location: "Fort-Royal, Martinique",
    owner: "M. de Vaugirard",
    source: "Registre de l'état civil libre, 1831",
    notes: "Inscrite sous le nom patronymique « Léger » par décision officielle.",
  },
  {
    id: "aff_005",
    type: "affranchissement",
    name: "Jean-Louis Toussaint",
    age: "37 ans",
    date: "1848-04-27",
    location: "Saint-Pierre, Martinique",
    source: "Décret du 27 avril 1848 — Abolition de l'esclavage",
    notes: "Affranchissement général. Nouveau nom de famille attribué : Lestin.",
  },

  // ── Registre des esclaves (recensements) ───────────────────────────
  {
    id: "esc_001",
    type: "esclave",
    name: "Habitation Clément — recensement",
    date: "1817",
    location: "Le François, Martinique",
    owner: "Famille Clément",
    source: "Recensement nominatif de 1817, ANOM",
    notes:
      "127 personnes recensées : 58 hommes, 64 femmes, 5 enfants en bas âge.",
  },
  {
    id: "esc_002",
    type: "esclave",
    name: "Émilie",
    age: "16 ans",
    date: "1826-01-01",
    location: "Habitation Sainte-Marie, Guadeloupe",
    origin: "Née dans la colonie",
    owner: "Sieur Boudet",
    source: "Matricule individuelle n°4421",
    notes: "Tâches : domestique. Mère : Marguerite, matricule 4128.",
  },
  {
    id: "esc_003",
    type: "esclave",
    name: "Habitation La Mahaudière — recensement",
    date: "1840",
    location: "Anse-Bertrand, Guadeloupe",
    owner: "M. Douillard-Mahaudière",
    source: "Procès-verbal de visite, archives départementales",
    notes:
      "Procès retentissant relatif aux conditions de détention des esclaves.",
  },
  {
    id: "esc_004",
    type: "esclave",
    name: "Habitation Bréda — recensement",
    date: "1772",
    location: "Plaine du Nord, Saint-Domingue",
    owner: "Comte de Noé",
    source: "Inventaire après décès, étude Grimperel",
    notes: "Mention de Toussaint, cocher, 33 ans environ.",
  },
  {
    id: "esc_005",
    type: "esclave",
    name: "Habitation Beauport — recensement",
    date: "1836",
    location: "Le Moule, Guadeloupe",
    owner: "Famille Coquille-Dupuy",
    source: "Registre des matricules, série 6M",
    notes: "243 individus matriculés, dont 31 enfants nés depuis 1830.",
  },

  // ── Cartes de migration ────────────────────────────────────────────
  {
    id: "mig_001",
    type: "migration",
    name: "Adèle Pétronille",
    date: "1854-06-12",
    origin: "Pointe-à-Pitre, Guadeloupe",
    destination: "Colón, Panama",
    source: "Liste des passagers — vapeur La Sémillante",
    notes: "Engagée pour les travaux du chemin de fer transisthmique.",
  },
  {
    id: "mig_002",
    type: "migration",
    name: "François Désiré Auguste",
    date: "1923-09-04",
    origin: "Saint-Pierre, Martinique",
    destination: "Le Havre, France",
    source: "Manifeste passagers — Compagnie Générale Transatlantique",
    notes: "Carte d'identité coloniale n°M-1923-0871.",
  },
  {
    id: "mig_003",
    type: "migration",
    name: "Solange Marie-Claire",
    date: "1963-04-18",
    origin: "Fort-de-France, Martinique",
    destination: "Paris (Orly), France",
    source: "BUMIDOM — registre des arrivées 1963",
    notes:
      "Affectée comme aide-soignante à l'hôpital de la Pitié-Salpêtrière.",
  },
  {
    id: "mig_004",
    type: "migration",
    name: "Hippolyte Saint-Cyr",
    date: "1916-02-22",
    origin: "Cayenne, Guyane française",
    destination: "Marseille, France",
    source: "Registre de mobilisation — Bataillon des Antilles",
    notes:
      "Mobilisé dans le cadre de la Première Guerre mondiale, retour en 1919.",
  },
  {
    id: "mig_005",
    type: "migration",
    name: "Eulalie Joséphine",
    date: "1909-11-30",
    origin: "Saint-Louis du Sénégal",
    destination: "Bordeaux, France",
    source: "Liste de débarquement — port de Bordeaux",
    notes: "Accompagnée de deux enfants : Joseph (4 ans) et Marie (2 ans).",
  },
  {
    id: "mig_006",
    type: "migration",
    name: "Léopold Boniface",
    date: "1937-07-08",
    origin: "Cotonou, Dahomey",
    destination: "Dakar, AOF",
    source: "Registre des déplacements intérieurs AOF",
    notes: "Affecté comme commis à l'administration coloniale.",
  },
];

export const ARCHIVE_LABELS: Record<
  ArchiveRecord["type"],
  { title: string; subtitle: string; sourceHint: string }
> = {
  fugitif: {
    title: "Registre des fugitifs",
    subtitle:
      "Avis de fuite et descriptions publiés dans les gazettes coloniales.",
    sourceHint: "Affiches américaines · Gazettes coloniales · ANOM",
  },
  affranchissement: {
    title: "Registre des affranchissements",
    subtitle:
      "Actes de libération individuelle, rachats et affranchissements collectifs.",
    sourceHint: "ANOM Série G · Études notariales · Décret de 1848",
  },
  esclave: {
    title: "Registre des esclaves",
    subtitle:
      "Recensements nominatifs, matricules d'habitation et inventaires.",
    sourceHint: "Recensements coloniaux · Inventaires après décès",
  },
  migration: {
    title: "Cartes de migration",
    subtitle:
      "Listes de passagers, manifestes maritimes et registres d'arrivée.",
    sourceHint: "BUMIDOM · Compagnies maritimes · Archives portuaires",
  },
};
